#!/bin/bash
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, make this file executable by "chmod +x post-update".

export GIT_DIR=/var/www/www.gul.uc3m.es/git/project.git 
export GIT_WORK_TREE=/var/www/www.gul.uc3m.es/git/web/project
cd $GIT_WORK_TREE
git reset --hard HEAD
make
exit 0
